apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: <zerossl-key-id>
      keySecretRef:
        name: zerossl-eab-secret
        key: secret
    privateKeySecretRef:
      name: zerossl-production
    solvers:
    - dns01:
        route53:
          region: eu-west-1
          accessKeyID: <aws-access-key-id>
          secretAccessKeySecretRef:
            name: route53-credentials
            key: secret

